name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    branches:
      - "*"

# Declare default permissions as read only
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-kafka-oauth:
    name: Build & Test Kafka OAuth
    strategy:
      matrix:
        java:
          # Java 17 is used as default version
          # In case of adding new version make sure that build-containers and deploy-java has correct static version set
          - version: "17"
            mainBuild: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@main
        with:
          javaVersion: ${{ matrix.java.version }}

      - name: Build binaries using build-binaries action
        uses: strimzi/github-actions/.github/actions/build/build-binaries@main
        with:
          mainJavaBuild: ${{ matrix.java.mainBuild }}
          artifactSuffix: "kafka-oauth"
          clusterOperatorBuild: "false"

  test-kafka-oauth:
    name: Run OAuth testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@main
        with:
          javaVersion: "17"

      - name: Run OAuth testsuite
        uses: ./.github/actions/build/test-oauth

  deploy-java:
    name: Deploy Java artifacts to Maven Central
    needs:
      - build-kafka-oauth
      - test-kafka-oauth
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@main
        with:
          javaVersion: "17"

      - name: Deploy to Maven Central
        uses: strimzi/github-actions/.github/actions/build/deploy-java@main
        with:
          modules: "./"
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpgSigningKey: ${{ secrets.GPG_SIGNING_KEY }}
          centralUsername: ${{ secrets.CENTRAL_USERNAME }}
          centralPassword: ${{ secrets.CENTRAL_PASSWORD }}