name: GitHub Actions Integration

on:
  pull_request:
    paths:
      - '**/pom.xml'
      - 'Makefile'
      - 'Makefile.maven'
      - 'Makefile.os'
      - '.github/workflows/github-actions-integration.yml'
    branches:
      - "*"

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-github-actions-integration:
    uses: strimzi/github-actions/.github/workflows/reusable-test-integrations.yml@v1
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.sha }}
      architecture: "amd64"
      artifactSuffix: "kafka-oauth"
      buildContainers: false
      modules: "!examples/producer','!examples/consumer"
      nexusCheck: "kafka-oauth-common"
      javaVersion: "17"
      helmChartName: "none"
      releaseVersion: "6.6.6"
      imagesDir: "none"
      clusterOperatorBuild: false
      githubActionsRef: "v1"
    secrets: inherit