---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 4.3.0
    metadataVersion: 4.3-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            sasl.enabled.mechanisms: OAUTHBEARER,PLAIN
            oauthbearer.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
            plain.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.plain.JaasServerOauthOverPlainValidatorCallbackHandler
            oauthbearer.sasl.jaas.config: |
              org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required unsecuredLoginStringClaim_sub="thePrincipalName" oauth.valid.issuer.uri="http://keycloak:8080/realms/kafka-authz" oauth.jwks.endpoint.uri="http://keycloak:8080/realms/kafka-authz/protocol/openid-connect/certs" oauth.username.claim="preferred_username" ;
            plain.sasl.jaas.config: |
              org.apache.kafka.common.security.plain.PlainLoginModule required oauth.valid.issuer.uri="http://keycloak:8080/realms/kafka-authz" oauth.jwks.endpoint.uri="http://keycloak:8080/realms/kafka-authz/protocol/openid-connect/certs" oauth.token.endpoint.uri="http://keycloak:8080/realms/kafka-authz/protocol/openid-connect/token" oauth.username.claim="preferred_username" ;
            connections.max.reauth.ms: 3600
    authorization:
      type: custom
      authorizerClass: io.strimzi.kafka.oauth.server.authorizer.KeycloakAuthorizer
      superUsers:
      - User:service-account-kafka
    config:
      # Needed for Oauth authentication and Keycloak authorization
      principal.builder.class: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
      # Needed for Keycloak authorization
      strimzi.authorization.client.id: kafka
      strimzi.authorization.token.endpoint.uri: http://keycloak:8080/realms/kafka-authz/protocol/openid-connect/token
      strimzi.authorization.ssl.endpoint.identification.algorithm: ""
      strimzi.authorization.delegate.to.kafka.acl: "true"
      # Other Kafka configuration options
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    logging:
      type: inline
      loggers:
        logger.io_strimzi.name: "io.strimzi"
        logger.io_strimzi.level: "TRACE"
        logger.io_strimzi.appenderRefs: "console"
        logger.io_strimzi.appenderRef.console.ref: "STDOUT"
        logger.kafka.name: "kafka"
        logger.kafka.level: "INFO"
        logger.org_apache_kafka.name: "org.apache.kafka"
        logger.org_apache_kafka.level: "INFO"

    # Uncomment if file access denied    
    #template:
    #  pod:
    #    securityContext:
    #      fsGroup: 0
  entityOperator:
    topicOperator: {}
    userOperator: {}
