---
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 4.3.0
    metadataVersion: 4.3-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            sasl.enabled.mechanisms: OAUTHBEARER
            oauthbearer.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
            oauthbearer.sasl.jaas.config: |
              org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required unsecuredLoginStringClaim_sub="thePrincipalName" oauth.introspection.endpoint.uri="http://spring:8080/oauth/check_token" oauth.client.id="kafka" oauth.client.secret="${secrets:my-cluster/my-cluster-kafka-client-secret:secret}" oauth.check.issuer="false" oauth.access.token.is.jwt="false" oauth.username.claim="user_name" oauth.fallback.username.claim="client_id" oauth.fallback.username.prefix="client-account-" ;
    logging:
      type: inline
      loggers:
        logger.io_strimzi.name: "io.strimzi"
        logger.io_strimzi.level: "DEBUG"
        logger.io_strimzi.appenderRefs: "console"
        logger.io_strimzi.appenderRef.console.ref: "STDOUT"
    config:
      # Needed for Oauth authentication
      principal.builder.class: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
      # Other Kafka configuration options
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    
    # Uncomment if file access denied
    #template:
    #  pod:
    #    securityContext:
    #      fsGroup: 0
  entityOperator:
    topicOperator: {}
    userOperator: {}
